application: waste-hrd
version: prod
runtime: python27
api_version: 1
threadsafe: false


handlers:
- url: /favicon.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon.ico


- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt


- url: /css
  static_dir: static/css
- url: /img
  static_dir: static/img
- url: /js
  static_dir: static/js
- url: /ico
  static_dir: static/ico
- url: /fonts
  static_dir: static/fonts

- url: /static
  static_dir: static

- url: /admin/.*
  script: $PYTHON_LIB/apphosting/ext/admin/

- url: /_ereporter.*
  script: google.appengine.ext.ereporter.report_generator.application
  login: admin

- url: /tasks/.*
  script: tasks.py
  login: admin

- url: /.*
  script: main.py

libraries:
- name: django
  version: "1.4"
- name: lxml
  version: latest

builtins:
- appstats: on
