"""
Django settings for waste_d project.

Generated by 'django-admin startproject' using Django 3.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

import os
from pathlib import Path
from google.cloud import secretmanager
import logging
from wasted_project import DJANGO_ENV_DEV, DJANGO_ENV_PROD

log = logging.getLogger(__name__)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

pid = os.getpid()
log.info("[%d] Django environment determined as: %s" % (pid, os.environ['DJANGO_ENV']))


# Create the Secret Manager client.
client = secretmanager.SecretManagerServiceClient()

# Get the Django secrect key
secret_path = "projects/%s/secrets/%s/versions/latest" % (os.environ['GOOGLE_CLOUD_PROJECT'], 'django-secret_key')
response = client.access_secret_version(request={"name": secret_path})
SECRET_KEY = response.payload.data.decode("UTF-8")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []
if "GCP_RUN_HOSTS" in os.environ:
    ALLOWED_HOSTS.extend(os.environ['GCP_RUN_HOSTS'].split(','))

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_extensions',
    'rest_framework',
    'rest_framework.authtoken',
    # Own ones:
    'waste_d.apps.WastedConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'waste_d.datastore.cloud-ndb.django_middleware.ndb_django_middleware'
]

ROOT_URLCONF = 'wasted_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['waste_d/templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'wasted_project.wsgi.application'

# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

secret_path = "projects/%s/secrets/%s/versions/latest" % (os.environ['GOOGLE_CLOUD_PROJECT'], 'mysql-app-user')
response = client.access_secret_version(request={"name": secret_path})
mysql_hostname = '68.171.228.35.bc.googleusercontent.com'
mysql_database = 'waste.d'
mysql_user = 'wappd'
mysql_password = response.payload.data.decode("UTF-8")

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'HOST': mysql_hostname,
        'USER': mysql_user,
        'PASSWORD': mysql_password,
        'NAME': mysql_database,
    }
}

# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
    ],
}

# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

MEDIA_URL = None
if "GCP_STATIC_URL" in os.environ:
    STATIC_URL = os.environ['GCP_STATIC_URL']
    log.info("Serving static files from: %s" % STATIC_URL)
else:
    log.info("Serving static files from Django")
    STATIC_URL = '/static/'
    STATICFILES_DIRS = [
        "%s/static" % BASE_DIR,
    ]


# Query for region?
if 'GCP_REGION' not in os.environ and os.environ['DJANGO_ENV'] == DJANGO_ENV_PROD:
    import requests

    meta_url = 'http://metadata.google.internal/computeMetadata/v1/instance/region'
    r = requests.get(meta_url)
    r.raise_for_status()
    log.info('[%d] Meta request for %s returned: "%s"' % (pid, meta_url, r.text))
    os.environ['GCP_REGION'] = r.text.rstrip()

    for env_var in os.environ:
        log.error("error Env: '%s' = '%s'" % (env_var, os.environ[env_var]))
        log.info("info Env: '%s' = '%s'" % (env_var, os.environ[env_var]))
