# Generated by Django 3.1.3 on 2020-11-16 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Counter',
            fields=[
                ('name', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='counter_name')),
                ('count', models.IntegerField()),
            ],
        ),
    ]
