# Generated by Django 3.1.3 on 2020-11-17 11:03

from django.db import migrations, models
import django.utils.timezone
import waste_d.models.sql.fields.timestamp


class Migration(migrations.Migration):

    dependencies = [
        ('waste_d', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='counter',
            name='idate',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='counter',
            name='ts',
            field=waste_d.models.sql.fields.timestamp.TimestampField(auto_created=True, auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
