# Generated by Django 3.1.3 on 2020-12-27 19:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('waste_d', '0002_auto_20201117_1103'),
    ]

    operations = [
        migrations.CreateModel(
            name='WastedToken',
            fields=[
                ('key', models.CharField(max_length=40, primary_key=True, serialize=False, verbose_name='Key')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('platform', models.CharField(max_length=20, verbose_name='Platform')),
                ('chat', models.CharField(max_length=40, null=True, verbose_name='Chat')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wasted_auth_token', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Token',
                'verbose_name_plural': 'Tokens',
                'db_table': 'authtoken_wasted_token',
                'abstract': False,
            },
        ),
    ]
